import { defineTool, readOnly, createOnly, updateOnly, type StudioTool } from "./define.js";
import {
  dayField,
  idField,
  limitField,
  milestoneStatusField,
  nameField,
  projectStatusField,
  queryField,
  taskPriorityField,
  taskStatusField,
  textField,
} from "./schemas.js";

export const deliveryTools: StudioTool[] = [
  defineTool({
    name: "project_list",
    title: "List projects",
    description: "List projects. Optionally filter by client, status, or text.",
    inputSchema: {
      clientId: idField.optional().describe("Filter by client id."),
      status: projectStatusField.optional(),
      query: queryField.optional(),
      limit: limitField,
    },
    annotations: readOnly,
    handler: (args, studio) => studio.listProjects(args),
  }),
  defineTool({
    name: "project_get",
    title: "Get project",
    description: "Get one project by id.",
    inputSchema: { id: idField.describe("Project id.") },
    annotations: readOnly,
    handler: (args, studio) => studio.getProject(args),
  }),
  defineTool({
    name: "project_create",
    title: "Create project",
    description: "Create a project for an existing client. Status defaults to planning.",
    inputSchema: {
      clientId: idField.describe("Client id."),
      name: nameField.describe("Project name."),
      status: projectStatusField.optional().describe("Defaults to planning."),
      phase: nameField.optional().describe("Current phase label."),
      startDate: dayField.optional(),
      dueDate: dayField.optional(),
      description: textField.optional(),
    },
    annotations: createOnly,
    handler: (args, studio) => studio.createProject(args),
  }),
  defineTool({
    name: "project_update",
    title: "Update project",
    description: "Update a project. Omitted fields stay unchanged.",
    inputSchema: {
      id: idField.describe("Project id."),
      name: nameField.optional(),
      status: projectStatusField.optional(),
      phase: nameField.optional(),
      startDate: dayField.optional(),
      dueDate: dayField.optional(),
      description: textField.optional(),
    },
    annotations: updateOnly,
    handler: (args, studio) => studio.updateProject(args),
  }),
  defineTool({
    name: "milestone_list",
    title: "List milestones",
    description: "List milestones on a project, earliest due date first.",
    inputSchema: {
      projectId: idField.describe("Project id."),
      status: milestoneStatusField.optional(),
      limit: limitField,
    },
    annotations: readOnly,
    handler: (args, studio) => studio.listMilestones(args),
  }),
  defineTool({
    name: "milestone_upsert",
    title: "Upsert milestone",
    description:
      "Update a milestone by id, or create/update one by projectId and name. Matching name on that project updates the existing milestone.",
    inputSchema: {
      id: idField.optional().describe("Milestone id. When set, updates that milestone."),
      projectId: idField.optional().describe("Required when id is omitted."),
      name: nameField.optional().describe("Required when id is omitted. Also the match key."),
      status: milestoneStatusField.optional().describe("Defaults to pending on create."),
      dueDate: dayField.optional(),
      description: textField.optional(),
    },
    annotations: updateOnly,
    handler: (args, studio) => studio.upsertMilestone(args),
  }),
  defineTool({
    name: "task_list",
    title: "List tasks",
    description: "List tasks. Filter by project, milestone, assignee, status, or text.",
    inputSchema: {
      projectId: idField.optional(),
      milestoneId: idField.optional(),
      assigneeId: idField.optional().describe("Member id."),
      status: taskStatusField.optional(),
      query: queryField.optional(),
      limit: limitField,
    },
    annotations: readOnly,
    handler: (args, studio) => studio.listTasks(args),
  }),
  defineTool({
    name: "task_get",
    title: "Get task",
    description: "Get one task and its comments.",
    inputSchema: { id: idField.describe("Task id.") },
    annotations: readOnly,
    handler: (args, studio) => studio.getTask(args),
  }),
  defineTool({
    name: "task_create",
    title: "Create task",
    description: "Create a task on a project. Status defaults to todo and priority defaults to normal.",
    inputSchema: {
      projectId: idField.describe("Project id."),
      milestoneId: idField.optional().describe("Milestone on the same project."),
      title: nameField.describe("Task title."),
      description: textField.optional(),
      status: taskStatusField.optional(),
      assigneeId: idField.optional().describe("Member id."),
      dueDate: dayField.optional(),
      priority: taskPriorityField.optional(),
    },
    annotations: createOnly,
    handler: (args, studio) => studio.createTask(args),
  }),
  defineTool({
    name: "task_update",
    title: "Update task",
    description: "Update a task. Omitted fields stay unchanged. The task stays on its project.",
    inputSchema: {
      id: idField.describe("Task id."),
      milestoneId: idField.optional(),
      title: nameField.optional(),
      description: textField.optional(),
      status: taskStatusField.optional(),
      assigneeId: idField.optional(),
      dueDate: dayField.optional(),
      priority: taskPriorityField.optional(),
    },
    annotations: updateOnly,
    handler: (args, studio) => studio.updateTask(args),
  }),
  defineTool({
    name: "task_comment",
    title: "Comment on task",
    description: "Add a comment to a task.",
    inputSchema: {
      taskId: idField.describe("Task id."),
      body: textField.describe("Comment body."),
      authorId: idField.optional().describe("Member id of the author."),
    },
    annotations: createOnly,
    handler: (args, studio) => studio.commentOnTask(args),
  }),
  defineTool({
    name: "delivery_status",
    title: "Delivery status",
    description:
      "Roll up a project's milestones and tasks. Health is delivered, then blocked, then at_risk when a milestone is overdue, otherwise on_track.",
    inputSchema: { projectId: idField.describe("Project id.") },
    annotations: readOnly,
    handler: (args, studio) => studio.deliveryStatus({ id: args.projectId }),
  }),
];
