import { defineTool, readOnly, createOnly, updateOnly, type StudioTool } from "./define.js";
import {
  idField,
  leadStageField,
  limitField,
  nameField,
  proposalStatusField,
  queryField,
  textField,
} from "./schemas.js";
import { z } from "zod";

export const pipelineTools: StudioTool[] = [
  defineTool({
    name: "lead_list",
    title: "List leads",
    description: "List pipeline leads. Filter by stage, owner, or text.",
    inputSchema: {
      stage: leadStageField.optional(),
      ownerId: idField.optional().describe("Member id."),
      query: queryField.optional(),
      limit: limitField,
    },
    annotations: readOnly,
    handler: (args, studio) => studio.listLeads(args),
  }),
  defineTool({
    name: "lead_get",
    title: "Get lead",
    description: "Get one lead by id.",
    inputSchema: { id: idField.describe("Lead id.") },
    annotations: readOnly,
    handler: (args, studio) => studio.getLead(args),
  }),
  defineTool({
    name: "lead_create",
    title: "Create lead",
    description: "Create a lead. Stage defaults to new.",
    inputSchema: {
      name: nameField.describe("Lead or company name."),
      company: nameField.optional(),
      email: z.string().trim().email().optional(),
      source: nameField.optional().describe("How the lead arrived, such as referral."),
      stage: leadStageField.optional().describe("Defaults to new."),
      ownerId: idField.optional().describe("Member id."),
      notes: textField.optional(),
    },
    annotations: createOnly,
    handler: (args, studio) => studio.createLead(args),
  }),
  defineTool({
    name: "lead_update",
    title: "Update lead",
    description: "Update a lead. Omitted fields stay unchanged.",
    inputSchema: {
      id: idField.describe("Lead id."),
      name: nameField.optional(),
      company: nameField.optional(),
      email: z.string().trim().email().optional(),
      source: nameField.optional(),
      stage: leadStageField.optional(),
      ownerId: idField.optional(),
      notes: textField.optional(),
    },
    annotations: updateOnly,
    handler: (args, studio) => studio.updateLead(args),
  }),
  defineTool({
    name: "proposal_list",
    title: "List proposals",
    description: "List proposals. Filter by lead, client, status, or text.",
    inputSchema: {
      leadId: idField.optional(),
      clientId: idField.optional(),
      status: proposalStatusField.optional(),
      query: queryField.optional(),
      limit: limitField,
    },
    annotations: readOnly,
    handler: (args, studio) => studio.listProposals(args),
  }),
  defineTool({
    name: "proposal_get",
    title: "Get proposal",
    description: "Get one proposal by id.",
    inputSchema: { id: idField.describe("Proposal id.") },
    annotations: readOnly,
    handler: (args, studio) => studio.getProposal(args),
  }),
  defineTool({
    name: "proposal_create",
    title: "Create proposal",
    description: "Create a proposal. Status defaults to draft and currency defaults to USD.",
    inputSchema: {
      title: nameField.describe("Proposal title."),
      leadId: idField.optional(),
      clientId: idField.optional(),
      status: proposalStatusField.optional(),
      amount: z.number().nonnegative().finite().optional().describe("Amount in currency units."),
      currency: z.string().trim().min(3).max(3).optional().describe("ISO currency code. Defaults to USD."),
      summary: textField.optional(),
    },
    annotations: createOnly,
    handler: (args, studio) => studio.createProposal(args),
  }),
  defineTool({
    name: "pipeline_summary",
    title: "Pipeline summary",
    description: "Summarize lead stages and proposal amounts. Open amount includes draft and sent proposals.",
    inputSchema: {},
    annotations: readOnly,
    handler: (_args, studio) => studio.pipelineSummary(),
  }),
];
